name: Build manylinux wheel

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build wheel (manylinux2014, Python 3.8)
      uses: RalfG/python-wheels-manylinux-build@v0.4.2
      with:
        python-versions: "cp38"
        package-path: .
        build-requirements: "pybind11"

    - name: Upload built wheel
      uses: actions/upload-artifact@v4
      with:
        name: my_ctools-manylinux-wheel
        path: dist/*.whl
